### PR TITLE
Update config file for new platforms.

### PR DESCRIPTION
**Pull request by olawlor**
Currently the repo doesn't build on aarch64 machines like Raspberry Pi 4 because the config.guess script is from 2009.

This is the updated GNU config.guess file that does build successfully on a Raspberry Pi 4.

### CODE REVIEW

**Comment by jtv** [comment]
Thank you!  Haven't paid any attention to this for _years._

I'm slipping #689 in ahead of this one as a lazy way to verify this version of the script against upstream.

**Comment by jtv** [comment]
Okay, I _had_ expected Github to re-generate the diff after I merged my other branch.  Clearly that's not happening.  How I miss Launchpad and bzr!

@olawlor any chance you could trigger a fresh diff, e.g. by adding a commit, or rebasing?  (The risk of rebasing is that you may see a lot of conflicts if your updated version of config.guess does not match mine.)

**Comment by olawlor** [comment]
'diff' shows you grabbed exactly the same version as me, so this pull request is done!

It looks like github automatically closed my side of the request when I force-pushed your commit to my repo.  Thanks for updating this!

**Comment by jtv** [comment]
Excellent, thanks for pushing this forward.

**Pull request closed without merging**
