### PR TITLE
Read blob to std::vector and raw buffer

### PR DESCRIPTION
**Pull request by elelel**
This PR addresses concerns expressed in #400, #427 and some other as described below.

- std::basic_string is not an appropriate type to return blobs, it is designed to store user readable text strings. It differs from std::vector mainly by char_traits template parameter, that describes ordering in a particular human alphabet, equality of characters for things like case insensitive comparison, etc. There is no reason to assume that blobs should be user readble string. Using std::byte as T is particularily inappropriate, because there's no default specialization for it in standard lib, and it uses default template, which is char oriented. This PR adds reading to std::vector instead.
- Since there's no equivalent in C++ of reading raw C buffers that are performance-equivalent, a pass-through interface to C buffer API is provided for the cases when using STL containers is a concern for performance or interoperability reasons.
- Using a concrete template type instantiation prevents the user of using her own element type and allocator. Efficient memory allocation or zero cost construction is impossible in this case. 
- Putting both the container, that has size state and separate size parameter into function's signature is confusing for user, makes unclear how they are reconciled and hides the dangers of not preallocating container's memory with care before making the calls to the function
- Each call to resize() in worst case potentially leads to one additional memory allocation of the size requested, one additional read/write of existing buffer's size, or a write of 0s of the size of new buffer's size due to default-construction of element type. In this PR no resize() is called in library's functions and a notice in documentation is added in case the user decides to do it on her own anyway.

### CODE REVIEW

**Comment by jtv** [comment]
Just summarising our discussion elsewhere:

You're right that the lack of genericity is annoying.  The caller ought to have a lot more choice.  The reason is that I've been moving away from endless overloads, and I needed a simpler range of types.  How do we represent a buffer of raw bytes?  For years I've been painfully juggling `char *`, `unsigned char *`, `void *`, and `std::byte *` (and the array versions of course) along with `std::string_view` versus pointer/size pairs and pointer/pointer pairs, or the same for iterators, not to mention the container types.

For this particular function, the central insight from my perspective is that the caller specifies the maximum size, and so the resizing inside the function is really just an added convenience.  We don't _need_ resizing inside the function, because you're never going to get more bytes than you asked for.  So the most generic solution is to let the caller get the size right before making the call.  In the C++20 version of the function, you will pass in a `std::span<std::byte> buffer`, and you'll get an identical or smaller `std::span<std::byte>` back.  Your actual buffer may be a `std::string`, or a `char[]`, or a `void *`, or a `std::basic_string<unsigned char>`, or whatever kind of buffer you like.  You can `reinterpret_cast`, but it's your own problem.  The only restriction is that it be a contiguous range of writable bytes.  I'm hoping to start introducing these spans well before we go fully C++20.

So with apologies, I'd like to close this PR and go in the "span" direction.  I hate throwing away a good contribution, and I'm sorry for letting you walk into this situation.  In hindsight I should have added a TODO note to indicate the future direction.

**Comment by elelel** [comment]
Gien hat this PR differs from your summary only by the fact that it uses vector instead of span and:
- is std::byte-compatible (as any other type, uses just any T value type that user specifies)
- let's use specify the size the same way as with std::span, but using vector
... don't you want me to change it just to std::span from std::vector? It will make it pre-C++20 incompatible, of course.
Apart from what have been summarized it eliminates the need of most reinterpret_casts and it doesn't impose Allocator template parameter over user as it is currently with basic_string now. 

I don't mind closing the PR, just to would like a confirmation that every aspect of this PR is unacceptable before doing that.

**Comment by jtv** [comment]
Of course _not every aspect_ is incompatible with the direction had in mind!

I would love to have either…
 * something like this but as a compatible generalisation of the current string-based version, _or_
 * something for which the span-based version will later automatically become a compatible generalisation.

The latter could be done through a non-extending version that accepts a vector and/or string, or perhaps any container — _if_ we can find some pre-"span" way of enforcing the contiguity requirement for the underlying buffer.  We'd want it to return a "view" type, I think, for compatibility with `span` in the future, but the only pre-C++20 option I know of is `std::string_view<std::byte>`.

**Comment by elelel** [comment]
> something like this but as a compatible generalisation of the current string-based version

Relative to current string-based version, I restricted (specialized) two things: removed the size parameter and changed it from string to vector (which I'm not sure if s a restriction but maybe in some sense). Do you suggest returning the size parameter back? The other things are generalization, both for T and and Allocator parameter that basic_string has as well as vector. I could make a step back and recover the size parameter

> or perhaps any container — if we can find some pre-"span" way of enforcing the contiguity requirement for the underlying buffer

In pre-concepts era contiguity concept for containers (https://en.cppreference.com/w/cpp/named_req/ContiguousContainer) can be verified using static_asserts, like STL implementations do till this day, in concepts it can be simplified a bit. Both current basic_string and suggested vector variants pass that. std::span will not add any contiguity constraints over current. 

> We'd want it to return a "view" type, I think, for compatibility with span in the future, but the only pre-C++20 option I know of is std::string_view<std::byte>.

The question of ths PR is not returning, but the accepting the type of the buffer. blob::read function doesn't do anything with std::string_view, it requires std::basic_string as input parameter. That what creates problems. It requires that that potentially huge buffers is allocated with new/delete allocator (and nothing else, no memory pooling for example for frequent allocations), and then additionally makes calls to the allocator inside that potentially affect performance.

I don't want it to look that I'm trying to push the PR through, so I'm closing it. Still if you could explain the reasons about the points above that fail to grasp, I would be grateful. If not, it's ok as well :)

**Comment by jtv** [comment]
I see now that you've basically done the `vector` version exactly the way I'd like it in the future with `span`.  I'm sorry, that detail never sank in, what with all the other stuff going on.  There's only so much text you can usefully process on a phone!

Leaving out the size parameter disambiguates the difference, so that's good.  The size parameter will basically be what says "I'm going to resize this for you, and so this parameter overrides whatever sizes you have in there."

One slightly annoying thing with not having `span` is of course that `vector` itself already has two sizes: its "size" and its "capacity."  So we'll want to document that clearly.  But I think we can live with it — we can't actually _use_ the capacity for anything anyway.  Eventually the whole issue will go away as we generalise the `vector` to a `span`.

So yes, that part of the change does look fine, and the only part I really object to is the `void *` part.

**Comment by elelel** [comment]
I think the void* function should be just made private when we go C++20, and just use it internally to abstract our public interface over it. I overlooked the fact that span can almost be non-lossy replacement for raw pointers, as @JadeMatrix mentioned. Almost, because it forces to specify the size in number T elements, but I don't think anyone would have problems recalculating or need that at all. I also think that it's good to promote sane abstractions, but only if we don't take away anything significant from the user. The interface with strict string is far less flexible than unsafe C pointer in terms of resource management. So I think we should police the users and the abstractions they use only if we don't take anything away from them, especially if the library is a wrapper around another library whose functionality we're decreasing. I don't see a fully equivalent way of doing that C thing in pre-20 C++ abstractions.

**Comment by jtv** [comment]
Right, that's why I'm betting everything on `span`.  Without it, C++ has nothing better for this than C does: a pointer and size, or two pointers.  And I didn't want to do that simply because of overload crowding when `span` is around the corner.

**Comment by jtv** [comment]
#423 shows the API I had in mind.  It makes sense to start off with a `std::vector` version in that light, but returning the closest available pre-C++20 equivalent of `std::span`.

**Comment by jtv** [comment]
Er...  I'll close this one then.  Thanks @elelel for starting this discussion.

**Pull request closed without merging**
