### PR TITLE
Update `BUILDING-cmake.md`.

### PR DESCRIPTION
**Pull request by jtv**
See #558.  I'm not a CMake expert, but trying to follow along with
@GitSparTV and @tt4g and update the instructions.

### CODE REVIEW

**Comment by GitSparTV** [comment]
I think my template should be used as it is, just replacing my `toolgun` to `yourprojectname`

```cmake
cmake_minimum_required(VERSION 3.6)

project(project_name CXX)

IF (MSVC)
	# Ranges are available only in /std:c++latest (aka 23) on msvc
	set(CMAKE_CXX_STANDARD 23)
ELSE()
	set(CMAKE_CXX_STANDARD 20)
ENDIF()

add_executable(project_name main.cpp)

# If the library cannot be found, provide the root directly
# Example: -DPostgreSQL_ROOT="C:/Program Files/PostgreSQL/14/"
IF (PostgreSQL_ROOT AND POLICY CMP0074)
	cmake_policy(SET CMP0074 NEW)
ENDIF()

find_package(PostgreSQL REQUIRED)

set(SKIP_BUILD_TEST ON)

IF (WIN32)
	set(BUILD_SHARED_LIBS ON)
ELSE()
	set(BUILD_SHARED_LIBS OFF)
ENDIF()

set(LIBPQXXDIR CACHE STRING "libpqxx root directory")

add_subdirectory(${LIBPQXXDIR})
target_link_libraries(project_name PUBLIC pqxx PostgreSQL::PostgreSQL)
```

**Comment by tt4g** [comment]
I think the links to Issues related to the CMake project found so far will help. (#558, #504, #383, #235).
Because CMake is like a `Makefile` that we customize ourselves.

CMake supports a very large number of features to facilitate customization. This makes it difficult to understand CMake's features.
The way to build libpqxx with CMake is also various, such as "build libpqxx by itself", "import libpqxx into your project with `add_subdirectory()`", or "import libpqxx into your project with `FetchContent`".

Since many users who have trouble with CMake builds are likely to be unfamiliar with CMake's features, it is thought that an easy solution would be to learn from past Issues about solutions from people who have encountered similar problems to their own.

**Comment by jtv** [comment]
I like the idea of an example plus ways to find solutions when things go wrong.  Perhaps the documentation should link to a ticket search for "CMake" — not as specific as a list of examples, but it has the advantage that it stays up to date.  :-)

One question remains though: what's a good starting point for a CMakefile?  It should be short, and either minimise the number of implicit choices and decisions, or go with very good defaults.

**Comment by tt4g** [comment]
There are two main ways to import libpqxx into a CMake project: the first pattern is to use the installed libpqxx. In this case, we can use the libpqxx installed on the system with `find_package(libpqxx)` in the project.
The other pattern is to import libpqxx source code with `add_subdirectory()`. In this case, just calling `add_subdirectory(/path/to/libpqxx)` will import the CMake target `pqxx` into the project.

These are the two de facto standard ways to import libraries in CMake.

**Comment by GitSparTV** [comment]
Indeed it depends on how you include the library.
I have it in subdirectory because I cross-compile it on Windows and RaspbianOS. Perhaps I can even install libpqxx from apt-get and remove it from subdirectory

**Comment by jtv** [comment]
I just rewrote the initial part of `BUILDING-cmake.md`.  @GitSparTV @tt4g does it make more sense now?  I guess there are more things I need to tweak, such as incorporating the `IF (PostgreSQL_ROOT AND POLICY CMP0074)` once I can actually explain what it means.

**Comment by jtv** [comment]
Also, what does @KayEss think?

**Comment by tt4g** [comment]
Oops, I had missed the notification.
I think `BUILDING-cmake.md` is sufficient to understand how to build libpqxx.

**Comment by jtv** [comment]
> > Also, what does @KayEss think?
> 
> I like it. Looks likely to cover most people's questions.

Thank you.  I'll merge it then.

**Pull request merged**
